name: Delete Nested JSON Key

on: workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON File
        run: |
          echo '{
            "Reservations": [
              {
                "Instances": [
                  {
                    "InstanceId": "i-0abcd1234efgh5678",
                    "State": {"Name": "running"},
                    "PublicIpAddress": "3.92.183.54"
                  }
                ]
              }
            ]
          }' > instances.json

      - name: Delete Public IP from JSON
        run: |
          jq '.Reservations[0].Instances[0] |= del(.PublicIpAddress)' instances.json > temp.json && mv temp.json instances.json
          cat instances.json
