name: Pretty-Print JSON

on: workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Create Minified JSON
        run: |
          echo '{"id":"i-123","type":"t2.micro"}' > instance.json

      - name: Pretty Print JSON
        run: |
          jq '.' instance.json > pretty_instance.json
          cat pretty_instance.json
